# Default values for the netmaker helm chart. This is a YAML file.

# -- number of netmaker server replicas to create
replicas: 1

image:
  # -- The image repo to pull Netmaker image from
  repository: gravitl/netmaker
  # -- Pull Policy for images
  pullPolicy: IfNotPresent
  # -- Override the image tag to pull
  # tag: ""

# -- override the name for netmaker objects
nameOverride: ""

# -- override the full name for netmaker objects
fullnameOverride: ""

# -- optional tolerations settings for netmaker
tolerations: {}

# -- optional affinity settings for netmaker
affinity: {}
# example affinity
# affinity:
#   podAntiAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#     - labelSelector:
#         matchExpressions:
#         - key: app
#           operator: In
#           values:
#           - {{ include "netmaker.fullname" . }}
#       topologyKey: "kubernetes.io/hostname"

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- Name of SA to use. If not set and create is true, a name is generated using the fullname template
  name: ""

# -- pod annotations to add
podAnnotations: {}

# -- pod security contect to add
podSecurityContext: {}
# fsGroup: 2000

netmaker:
  serverName: "cluster.local"
  # -- ignored if netmaker.masterKeyExistingSecret is set
  masterKey: "netmaker"
  # -- Duration of JWT token validity in seconds
  jwtDuration: 43200
  # -- Auto disable a user's connecteds clients bassed on JWT token expiration
  racAutoDisable: "true"

  admin:
    # -- initial admin user to create. if set, disables registration via UI.
    # Ignored if netmaker.admin.existingSecret set
    user: ""
    # -- initial admin user's password, ignored if netmaker.admin.existingSecret set
    password: ""
    # -- set admin user/password via an existing k8s secret. Must have keys:
    # ADMIN_USER, ADMIN_PASSWORD
    # If set, disables registration via UI, and ignores netmaker.admin.user, netmaker.admin.password
    existingSecret: ""
    # -- restart policy for the admin user creation job
    jobRestartPolicy: "Never"

  # -- if using enterprise edition fill out this section
  enterprise:
    # -- netmaker enterprise license key, ignored if netmaker.existingSecret set
    licenseKey: ""
    # -- netmaker enterprise tenant ID, ignored if netmaker.existingSecret set
    tenantId: ""

  # -- if set ignores netmaker.masterKey and enterprise.*
  # must have key called MASTER_KEY, optionally for enterprise must have key:
  # LICENSE_KEY, NETMAKER_TENANT_ID
  existingSecret: ""

  # OAuth section
  oauth:
    enabled: false
    # -- AUTH_PROVIDER: must be one of: azure-ad|github|google|oidc
    provider: "oidc"
    # --  oidc issuer - ignored if netmaker.oauth.existingSecret is set
    issuer: ""
    # --  client id if using oidc - ignored if netmaker.oauth.existingSecret is set
    clientID: ""
    # --  client secret if using oidc - ignored if netmaker.oauth.existingSecret is set
    clientSecret: ""
    # --  azureTenant if using azure for oauth - ignored if netmaker.oauth.existingSecret is set
    azureTenant: ""
    # -- existing secret for oauth, must have the following keys:
    # CLIENT_ID, CLIENT_SECRET, OIDC_ISSUER, and optionally AZURE_TENANT
    # ignores plane text values if this is set
    existingSecret: ""

api:
  service:
    # -- type for netmaker server services
    type: ClusterIP
    # -- port for API service
    port: 8081
    # -- targetport for API service
    targetPort: 8081

  ingress:
    # -- attempts to configure ingress if true
    enabled: true
    # -- api (REST) route subdomain
    host: 'api.cluster.local'
    # -- api ingress className
    className: "nginx"
    # -- annotations for the netmaker API ingress object
    annotations: {}
    # -- ingress api tls list
    tls: []
    # tls:
    #   - secretName: netmaker-api-tls
    #     hosts:
    #       - api.mydomain.tld

ui:
  # -- how many UI replicas to create
  replicas: 1
  service:
    # -- type for netmaker server services
    type: ClusterIP
    # -- port for UI service
    port: 80
    # -- target port for UI service
    targetport: 80
  ingress:
    # -- attempts to configure ingress if true
    enabled: true
    # -- hostname for mqtt ingress
    host: "dashboard.cluster.local"
    # -- UI ingress className
    className: "nginx"
    # -- annotations for the netmaker UI ingress object
    annotations: {}
    # -- ingress tls list
    tls: []
    # tls:
    #   - secretName: netmaker-mqtt-tls
    #     hosts:
    #       - dashboard.mydomain.tld

mq:
  # -- how many MQTT replicas to create
  replicas: 1
  generateCert: false
  # -- optional tolerations settings for mqtt
  tolerations: {}
  # -- optional affinity settings for mqtt
  affinity: {}
  # nodeAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: mqhost
  #         operator: In
  #         values:
  #         - "true"
  username: netmaker
  password: ''
  # -- name of an existing secret to use for mq password. If set, ignores mq.password, mq.username
  # secret keys must be: MQ_PASSWORD, MQ_USERNAME
  existingSecret: ''
  service:
    # -- type for netmaker server services
    type: ClusterIP
    # -- port for MQTT service
    port: 443
    # -- Target port for MQTT service
    targetPort: 8883
  ingress:
    # -- attempts to configure ingress if true
    enabled: true
    # -- hostname for mqtt ingress
    host: "broker.cluster.local"
    className: "nginx"
    # -- annotations for the mqtt ingress object
    annotations: {}
    ## Redirect http to https
    # nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    ## destination addr for route
    # nginx.ingress.kubernetes.io/rewrite-target: /
    # -- ingress tls list
    tls: []
    # tls:
    #   - secretName: netmaker-mqtt-tls
    #     hosts:
    #       - broker.mydomain.tld

dns:
  # -- whether or not to deploy coredns
  enabled: false
  persistence:
    # -- existingClaim, if not set, defaults to HELM.RELEASE.NAME-dns
    existingClaim: ''
    storage: 1Gi
    storageClassName: ""
    accessMode: ReadWriteOnce

shared_data:
  persistence:
    # -- name of existing PVC claim to use. if set, storageClassName is ignored
    existingClaim: ""
    accessMode: "ReadWriteMany"
    storageClassName: ""
    storage: 128Mi

setIpForwarding:
  enabled: true

# https://github.com/bitnami/charts/tree/main/bitnami/postgresql#parameters
postgresql:
  # set to false if you want to use an existing postgres server.
  # if false, you must set the externalDatabase parameters
  enabled: true
  # postgresqlHostname: preexisting-postgresql
  # postgresqlPort: 5432
  auth:
    database: netmaker
    username: netmaker
    # you must set a password; the password generated by the postgresql chart will
    # be rotated on each upgrade:
    # https://github.com/bitnami/charts/tree/main/bitnami/postgresql#upgrade
    password: ""
    # -- use existing secret for netmaker db credentials, must have the following keys:
    # SQL_PASS, SQL_HOST, SQL_PORT, SQL_USER, SQL_DB
    existingSecret: ""
    primary:
      persistence:
        enabled: true
        # existingClaim: ''

# if postgresql.enabled is false, these values are used instead
externalDatabase:
  # type of database, only postgreql supported in this helm chart at this time
  type: postgresql
  # -- postgres host
  host: external.postgres.url
  # -- postgres hosts port
  port: 5432
  # -- postgres username
  username: netmaker
  # -- postgres pass for netmaker user. ignored if existingSecret is set
  password: ""
  # -- postgress db
  database: netmaker
  # -- use existing secret for netmaker db credentials, must have the following keys:
  # SQL_PASS, SQL_HOST, SQL_PORT, SQL_USER, SQL_DB
  existingSecret: ""

turn:
  # -- use an external turn server
  enabled: false
  host: ""
  apiHost: ""
  username: ""
  password: ""
  # -- existing secret with turn server info. Must have the following keys:
  # TURN_SERVER_HOST, TURN_SERVER_API_HOST, TURN_PORT, TURN_USERNAME, TURN_PASSWORD
  existingSecret: ""
