{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  SQL_HOST: "{{ include "netmaker.database.host" . }}"
  SQL_PORT: "{{ include "netmaker.database.port" . }}"
  SQL_DB: "{{ include "netmaker.database.database" . }}"
  SQL_USER: "{{ include "netmaker.database.username" . }}"
  SQL_PASS: "{{ include "netmaker.database.password" . }}"
  MQ_ADMIN_PASSWORD: {{ .Values.mq.password }}
{{- end }}
