---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "netmaker.labels" . | nindent 4 }}
  name: '{{ include "netmaker.fullname" . }}-api'
spec:
  ports:
    - name: api
      port: {{ .Values.api.service.port }}
      protocol: TCP
      targetPort: {{ .Values.api.service.targetPort }}
  selector:
    app: '{{ include "netmaker.fullname" . }}'
  sessionAffinity: None
  type: {{ .Values.api.service.type }}
