{{- if .Values.mq.ingress.generateCert }}
{{- $fullName := include "netmaker.fullname" . -}}
{{- $fullMQName := printf "%s-%s" $fullName "mqtt" -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    acme.cert-manager.io/http01-override-ingress-name: {{ $fullMQName }}
  labels:
    {{- include "netmaker.labels" . | nindent 4 }}
  name: {{ $fullMQName }}-tls-secret
spec:
  dnsNames:
  - {{ .Values.mq.ingress.hostname }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name:  {{ .Values.mq.ingress.tls.issuerName }}
  secretName: {{ $fullMQName }}-tls-secret
  usages:
  - digital signature
  - key encipherment
{{- end }}
