apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "netmaker.fullname" . }}
  labels:
    {{- include "netmaker.labels" . | nindent 4 }}
data:
  SERVER_NAME: broker.{{ required "A valid .Values.baseDomain entry required!" .Values.baseDomain}}
  SERVER_API_CONN_STRING: api.{{ required "A valid .Values.baseDomain entry required!" .Values.baseDomain}}:443
  SERVER_HTTP_HOST: api.{{ required "A valid .Values.baseDomain entry required!" .Values.baseDomain}}
  API_PORT: "8081"
  {{- if not .Values.wireguard.kernel }}
  WG_QUICK_USERSPACE_IMPLEMENTATION: wireguard-go
  {{- end }}
  {{- if .Values.dns.enabled }}
  DNS_MODE: "on"
  COREDNS_ADDR: {{ required "A valid .Values.dns.clusterIP entry required! Choose an IP from your k8s service IP CIDR" .Values.dns.clusterIP }}
  {{- else }}
  DNS_MODE: "off"
  {{- end }}
  CLIENT_MODE: "on"
  CORS_ALLOWED_ORIGIN: '*'
  DATABASE: postgres
  SQL_HOST: "{{ include "netmaker.database.host" . }}"
  SQL_PORT: "{{ include "netmaker.database.port" . }}"
  SQL_USER: "{{ include "netmaker.database.username" . }}"
  SQL_DB: "{{ include "netmaker.database.database" . }}"
  DISPLAY_KEYS: "on"
  MQ_HOST: {{ include "netmaker.fullname" . }}-mqtt
  MQ_PORT: "{{ .Values.service.mqPort }}"
  MQ_SERVER_PORT: "1883"
  MASTER_KEY: {{ include "netmaker.masterKey" . }}
  PLATFORM: "Kubernetes"
  VERBOSITY: "3"
  {{- if .Values.oauth.enabled }}
  AUTH_PROVIDER: {{ .Values.oauth.provider }}
  {{- end }}
