{{- if not .Values.postgresql.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  SQL_PASS: {{ include "netmaker.database.password" . | b64enc | quote }}
  SQL_HOST: {{ include "netmaker.database.host" . | trim | b64enc | quote }}
  SQL_PORT: {{ include "netmaker.database.port" . | b64enc | quote }}
  SQL_USER: {{ include "netmaker.database.username" . | b64enc | quote }}
  SQL_DB: {{ include "netmaker.database.database" . | b64enc | quote }}
{{- end }}
