{{- if and .Values.ingress.enabled (eq .Values.ingress.className "traefik") -}}
{{- $fullName := include "netmaker.fullname" . -}}
{{- $fullMQName := printf "%s-%s" $fullName "mqtt" -}}
{{- $mqSvcPort := 8883 -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $fullMQName }}
  labels:
    {{- include "netmaker.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`{{ .Values.ingress.hostPrefix.mq }}{{ .Values.baseDomain }}`)
    services:
    - name: {{ $fullMQName }}
      port: {{ $mqSvcPort }}
  tls:
    passthrough: true
    secretName: {{ $fullMQName }}-tls-secret
    domains:
    - main: {{ .Values.ingress.hostPrefix.mq }}{{ .Values.baseDomain }}
{{- end }}
