{{- if .Values.ingress.enabled -}}
{{- $fullName := include "netmaker.fullname" . -}}
{{- $fullRESTName := printf "%s-%s" $fullName "rest" -}}
{{- $restSvcPort := .Values.service.restPort -}}
{{- $classname := required "A valid .Values.ingress.className entry required! Please set this to your ingress class (nginx, traefik)" .Values.ingress.className}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullRESTName }}
  labels:
    {{- include "netmaker.labels" . | nindent 4 }}
  {{- with .Values.ingress }}
  annotations:
    {{- toYaml .annotations.base | nindent 4 }}
    {{- if or (eq .className "nginx") (eq .className "public") }}
    {{- toYaml .annotations.nginx | nindent 4 }}
    {{- end }}
    {{- if eq .className "traefik" }}
    {{- toYaml .annotations.traefik | nindent 4 }}
    {{- end }}
    {{- if and .tls.enabled (eq .tls.issuerName "" )}}
    {{- toYaml .annotations.tls | nindent 4 }}
    {{- else if .tls.enabled}}
    cert-manager.io/cluster-issuer: {{ .tls.issuerName }}
    {{- end }}
    {{- with .annotations.rest }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if (not (eq .Values.ingress.className "traefik")) }}
  ingressClassName:  {{ required "A valid .Values.ingress.className entry required!" .Values.ingress.className}}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostPrefix.rest }}{{ .Values.baseDomain }}
      secretName: {{ $fullRESTName }}-tls-secret
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hostPrefix.rest }}{{ .Values.baseDomain }}
      http:
        paths:
          - path: /
            {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullRESTName }}
                port:
                  number: {{ $restSvcPort }}
              {{- else }}
              serviceName: {{ $fullRESTName }}
              servicePort: {{ $restSvcPort }}
              {{- end }}
{{- end }}
