apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: {{ include "netmaker.fullname" . }}-mqtt
    app.kubernetes.io/name: {{ include "netmaker.fullname" . }}-mqtt
  name: {{ include "netmaker.fullname" . }}-mqtt-config
data:
  mosquitto.conf: |
    per_listener_settings false
    listener {{ .Values.mq.service.targetPort }}
    protocol websockets
    allow_anonymous false
    listener 1883
    protocol websockets
    allow_anonymous false
    password_file /mosquitto/password.txt
