apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netmaker.fullname" . }}-mqtt
  labels:
    app: {{ include "netmaker.fullname" . }}-mqtt
spec:
  selector:
    matchLabels:
      app: {{ include "netmaker.fullname" . }}-mqtt
  replicas:  {{ .Values.mq.replicas }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ include "netmaker.fullname" . }}-mqtt
    spec:
      {{- with .Values.mq.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.mq.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: mosquitto
          image: eclipse-mosquitto:openssl
          command: ["/mosquitto/config/wait.sh"]
          imagePullPolicy: Always

          env:
            - name: NETMAKER_SERVER_HOST
              value: https://{{ required "A valid .Values.mq.ingress.host entry required!" .Values.mq.ingress.host }}

          ports:
            - containerPort: 1883        
              name: mqtt
              protocol: TCP
            - containerPort: {{ .Values.mq.service.targetPort }}        
              name: mqtt2
              protocol: TCP

          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.mq.service.targetPort }}
            timeoutSeconds: 1

          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.mq.service.targetPort }}
            timeoutSeconds: 1

          startupProbe:
            failureThreshold: 30
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.mq.service.targetPort }}
            timeoutSeconds: 1

          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File

          resources: {}

          volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
            - name: wait-script
              mountPath: /mosquitto/config/wait.sh
              subPath: wait.sh

      volumes:
        - name: mosquitto-config
          configMap:
            name: {{ include "netmaker.fullname" . }}-mqtt-config

        - name: wait-script
          configMap:
            name: {{ include "netmaker.fullname" . }}-mqtt-wait
            defaultMode: 0744
