apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netmaker.fullname" . }}-mqtt
  labels:
    app: {{ include "netmaker.fullname" . }}-mqtt
spec:
  selector:
    matchLabels:
      app: {{ include "netmaker.fullname" . }}-mqtt
  replicas:  {{ .Values.mq.replicas }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ include "netmaker.fullname" . }}-mqtt
    spec:
      {{- with .Values.mq.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mq.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - env:
        - name: NETMAKER_SERVER_HOST
          value: https://api.{{ required "A valid .Values.baseDomain entry required!" .Values.baseDomain}}
        image: eclipse-mosquitto:openssl
        command: ["/mosquitto/config/wait.sh"]
        imagePullPolicy: Always
        name: mosquitto
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8883
          timeoutSeconds: 1
        ports:
        - containerPort: 1883        
          name: mqtt
          protocol: TCP
        - containerPort: 8883        
          name: mqtt2
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8883
          timeoutSeconds: 1
        resources: {}
        startupProbe:
          failureThreshold: 30
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8883
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mosquitto/config/mosquitto.conf
          name: mosquitto-config
          subPath: mosquitto.conf
        - mountPath: /mosquitto/config/wait.sh
          name: wait-script
          subPath: wait.sh
        - mountPath: /mosquitto/data
          name: shared-data
      volumes:
      - configMap:
          name: {{ include "netmaker.fullname" . }}-mqtt-config
        name: mosquitto-config
      - configMap:
          name: {{ include "netmaker.fullname" . }}-mqtt-wait
          defaultMode: 0744
        name: wait-script
      - name: shared-data
        persistentVolumeClaim:
        {{- if .Values.mq.existingClaim }}
          claimName: {{ .Values.mq.existingClaim }}
        {{- else }} 
          claimName: {{ include "netmaker.fullname" . }}-shared-data
        {{- end }}
