{{- if .Values.mq.ingress.enabled -}}
{{- $fullName := include "netmaker.fullname" . -}}
{{- $fullMQName := printf "%s-%s" $fullName "mqtt" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullMQName }}
  labels:
    {{- include "netmaker.labels" . | nindent 4 }}
  {{- with .Values.mq.ingress.annotations }}
  annotations:
    {{- toYaml . }}
  {{- end }}
spec:
  ingressClassName:  {{ required "A valid .Values.ingress.className entry required!" .Values.mq.ingress.className}}
  {{- with .Values.mq.ingress.tls }}
  tls:
    {{- toYaml . }}
  {{- end }}
  rules:
    - host: {{ .Values.mq.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullMQName }}
                port:
                  number: {{ .Values.mq.service.targetPort }}
{{- end }}
