{{- if not .Values.mq.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: mq-secret
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  MQ_PASSWORD: {{ .Values.mq.password | b64enc | quote }}
  MQ_USERNAME: {{ .Values.mq.username | b64enc | quote }}
{{- end }}
