{{- if and .Values.netmaker.admin.user (not .Values.netmaker.admin.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: netmaker-admin-secret
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  ADMIN_USER: {{ .Values.netmaker.admin.user | b64enc | quote }}
  ADMIN_PASSWORD: {{ .Values.netmaker.admin.password | b64enc | quote }}
{{- end }}
