{{- if and .Values.netmaker.oauth.enabled (not .Values.netmaker.oauth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: netmaker-oauth-secret
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  CLIENT_ID: {{ .Values.netmaker.oAuthclientID | b64enc | quote }}
  CLIENT_SECRET: {{ .Values.netmaker.oAuthClientSecret | b64enc | quote }}
  OIDC_ISSUER: {{ .Values.netmaker.oauth.issuer | b64enc | quote }}
  {{- if .Values.netmaker.oauth.azureTenant }}
  AZURE_TENANT: {{ .Values.netmaker.oauth.azureTenant | b64enc | quote }}
  {{- end }}
{{- end }}
