{{- if or .Values.netmaker.enterprise (not .Values.netmaker.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: netmaker-secret
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if not .Values.netmaker.existingSecret }}
  MASTER_KEY: {{ include "netmaker.masterKey" . | b64enc | quote }}
  {{- if .Values.netmaker.enterprise.licensekey }}
  LICENSE_KEY: {{ .Values.netmaker.enterprise.licensekey | b64enc | quote }} 
  NETMAKER_TENANT_ID: {{ .Values.netmaker.enterprise.tenantId | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
