apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ include "netmaker.fullname" . }}
  name: {{ include "netmaker.fullname" . }}
spec:
  replicas: {{ .Values.replicas }}
  serviceName: {{ include "netmaker.fullname" . }}-headless
  selector:
    matchLabels:
      app: {{ include "netmaker.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "netmaker.fullname" . }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "netmaker.fullname" . }}
          image: {{ include "netmaker.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "netmaker.fullname" . }}-env
            - secretRef:
                name: {{ include "netmaker.secret" . }}
            - secretRef:
                name: {{ include "netmaker.mq.secret" . }}
            - secretRef:
                name: {{ include "netmaker.db.secret" . }}
            {{- if .Values.netmaker.oauth.enabled }}
            - secretRef:
                name: {{ include "netmaker.oauth.secret" . }}
            {{- end }}
            {{- if .Values.turn.enabled -}}
            - secretRef:
                name: {{ include "netmaker.turn.secret" . }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.api.service.port }}
              protocol: TCP
          {{- if .Values.dns.enabled }}
          volumeMounts:
          - mountPath: /etc/netmaker/
            name: shared-data
          - name: dns-pvc
            mountPath: /root/config/dnsconfig
          {{- end }} {{/* end dns.enabled check for volumeMounts */}}
      {{- if .Values.dns.enabled }}
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          {{- if .Values.shared_data.persistence.existingClaim }}
          claimName: {{ .Values.shared_data.persistence.existingClaim }}
          {{- else }}
          claimName: {{ include "netmaker.fullname" . }}-shared-data
          {{- end }}
      - name: dns-pvc
        persistentVolumeClaim:
          {{- if .Values.dns.persistence.existingClaim }}
          claimName: {{ .Values.dns.persistence.existingClaim }}
          {{- else }}
          claimName: {{ include "netmaker.fullname" . }}-dns
          {{- end }}
      {{- end }} {{/* end if dns.enabled for volumes */}}
