{{- if or .Values.netmaker.admin.user .Values.netmaker.admin.existingSecret }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: setup-initial-user-job
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: setup-initial-user-pod
    spec:
      containers:
        - name: setup-initial-user
          image: curlimages/curl:latest
          command:
            - |-
              curl --location "https://$SERVER_HTTP_HOST/api/users/adm/createsuperadmin" \ 
                   --header 'Content-Type: application/json' \
                   --data "{'username':'$ADMIN_USER', 'password':'$ADMIN_PASSWORD'}"
          env:
            - name: SERVER_HTTP_HOST
              valueFrom:
                secretKeyRef:
                  key: SERVER_HTTP_HOST
                  name: {{ include "netmaker.secret" . }}
            - name: ADMIN_USER
              valueFrom:
                secretKeyRef:
                  key: ADMIN_USER
                  name: {{ include "netmaker.admin.secret" . }}
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: ADMIN_PASSWORD
                  name: {{ include "netmaker.admin.secret" . }}
{{- end }}
