apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if not .Values.postgresql.auth.existingSecret }}
  SQL_PASS: "{{ include "netmaker.database.password" . }}"
  {{- end }}
  {{- if not .Values.mq.existingSecret }}
  MQ_ADMIN_PASSWORD: {{ .Values.mq.password }}
  MQ_PASSWORD: {{ .Values.mq.password }}
  {{- end }}
  MASTER_KEY: {{ include "netmaker.masterKey" . }}
