{{- if not .Values.existingSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  SQL_USER: "{{ include "netmaker.database.username" . }}"
  SQL_PASS: "{{ include "netmaker.database.password" . }}"
  MQ_ADMIN_PASSWORD: {{ .Values.mq.password }}
{{- end }}
