{{- if and .Values.turn.enabled (not .Values.turn.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: turn-secret
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  TURN_SERVER_HOST: {{ .Values.turn.host | b64enc | quote }}
  TURN_SERVER_API_HOST: {{ .Values.turn.apiHost | b64enc | quote }}
  TURN_PORT: {{ .Values.turn.port | b64enc | quote }}
  TURN_USERNAME: {{ .Values.turn.username | b64enc | quote }}
  TURN_PASSWORD: {{ .Values.turn.password | b64enc | quote }}
{{- end -}}
