apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "netmaker.fullname" . }}-ui
  name: {{ include "netmaker.fullname" . }}-ui
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      app: {{ include "netmaker.fullname" . }}-ui
  template:
    metadata:
      labels:
        app: {{ include "netmaker.fullname" . }}-ui
    spec:
      containers:
        - name: {{ include "netmaker.fullname" . }}-ui
          image: {{ include "netmaker.ui.image" . }}
          ports:
            - containerPort: {{ .Values.ui.service.port }}
          env:
            - name: BACKEND_URL
              value: 'https://{{ required "A valid .Values.api.ingress.host entry required!" .Values.api.ingress.host}}'
      terminationGracePeriodSeconds: 15
