apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "netmaker.labels" . | nindent 4 }}
  name: '{{ include "netmaker.fullname" . }}-ui'
spec:
  ports:
    - port: {{ .Values.ui.service.port }}
      protocol: TCP
      targetPort: {{ .Values.ui.service.targetPort }}
  selector:
    app: '{{ include "netmaker.fullname" . }}-ui'
  sessionAffinity: None
  type: {{ .Values.ui.service.type }}
