---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "netmaker.labels" . | nindent 4 }}
  name: '{{ include "netmaker.fullname" . }}-wireguard'
  {{- with .Values.wireguard.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  externalTrafficPolicy: Local
  type: {{ .Values.wireguard.service.type }}
  ports:
  {{ $count := (add .Values.wireguard.networkLimit 1 | int) }}
  {{- range untilStep 1 $count 1 }}
  - port: {{ add 31820 . }}
    nodePort: {{ add 31820 . }}
    protocol: UDP
    targetPort: {{ add 31820 . }}
    name: wg-iface-{{ add 31820 . }}
  {{- end }}
  selector:
    app: '{{ include "netmaker.fullname" . }}'
